# -*- coding: utf-8 -*-
"""Problem II Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16TXIaMdO-cuMdL4oDj-riwitlaAg1EYz

# 0- Simulation Program
"""

import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

# Demand distributions for products A and B
def generate_demand_A():
    r = np.random.random()
    if r <= 0.15: return 1
    elif r <= 0.40: return 2
    elif r <= 0.65: return 3
    else: return 4

def generate_demand_B():
    r = np.random.random()
    if r <= 0.30: return 1
    elif r <= 0.60: return 2
    else: return 3

def generate_leadTime():
    r = np.random.random()
    if r <= 0.4: return 1
    elif r <= 0.75: return 2
    else: return 3

# Parameters
cycle_len = 4  # N = 4
days = int(input("Number of days? "))
cycles = days // cycle_len

# Initial conditions
initialShowroom_A = 5
initialShowroom_B = 5
initialInventory_A = 15
initialInventory_B = 15
maxShowroom_A = 5
maxShowroom_B = 5
maxShowroom_total = 10
maxInventory_total = 30
mA = 6
mB = 6

# Tracking lists for product A
Days_A = [0]
Showroom_A_Begin = [initialShowroom_A]
Inventory_A_Begin = [initialInventory_A]
Demand_A = [0]
Showroom_A_End = [initialShowroom_A]
Inventory_A_End = [initialInventory_A]
Shortage_A = [0]
Replenish_A = [0]  # Showroom replenishment orders (5 units)
Order_A = [0]     # Review period orders (mA=6)
LeadTime_A = [0]
AddAtDay_A = [0]
ComingOrders_A = [0] * (days + 1)

# Tracking lists for product B
Showroom_B_Begin = [initialShowroom_B]
Inventory_B_Begin = [initialInventory_B]
Demand_B = [0]
Showroom_B_End = [initialShowroom_B]
Inventory_B_End = [initialInventory_B]
Shortage_B = [0]
Replenish_B = [0]
Order_B = [0]
LeadTime_B = [0]
AddAtDay_B = [0]
ComingOrders_B = [0] * (days + 1)


for i in range(1, days + 1):
    Days_A.append(i)

    # Process incoming orders to Inventory at beginning of day
    Inventory_A_Begin.append(Inventory_A_End[i-1] + ComingOrders_A[i])
    Inventory_B_Begin.append(Inventory_B_End[i-1] + ComingOrders_B[i])
    # Showroom Beginning (after previous day's replenishments)
    Showroom_A_Begin.append(Showroom_A_End[i-1])
    Showroom_B_Begin.append(Showroom_B_End[i-1])

    # Daily demand
    Demand_A.append(generate_demand_A())
    Demand_B.append(generate_demand_B())
    currentDemand_A = Demand_A[i]
    currentDemand_B = Demand_B[i]

    # Showroom Ending after satisfying demand
    served_A = min(currentDemand_A, Showroom_A_Begin[i])
    served_B = min(currentDemand_B, Showroom_B_Begin[i])

    Showroom_A_End.append(Showroom_A_Begin[i] - served_A)
    Showroom_B_End.append(Showroom_B_Begin[i] - served_B)

    shortage_A = currentDemand_A - served_A
    shortage_B = currentDemand_B - served_B

    # Inventory Ending (before review orders)
    Inventory_A_End.append(Inventory_A_Begin[i])
    Inventory_B_End.append(Inventory_B_Begin[i])

    # Shortage and automatic Showroom replenishment (5 units)
    replenish_qty_A = 0
    if shortage_A > 0 and Inventory_A_Begin[i] > 0:
        replenish_qty_A = min(5, Inventory_A_Begin[i], maxShowroom_A - Showroom_A_End[i])
        Showroom_A_End[i] += replenish_qty_A
        Inventory_A_End[i] -= replenish_qty_A
    Replenish_A.append(replenish_qty_A)

    replenish_qty_B = 0
    if shortage_B > 0 and Inventory_B_Begin[i] > 0:
        replenish_qty_B = min(5, Inventory_B_Begin[i], maxShowroom_B - Showroom_B_End[i])
        Showroom_B_End[i] += replenish_qty_B
        Inventory_B_End[i] -= replenish_qty_B
    Replenish_B.append(replenish_qty_B)

    # Showroom total constraint (max 10 total)
    total_showroom = Showroom_A_End[i] + Showroom_B_End[i]
    if total_showroom > maxShowroom_total:
        excess = total_showroom - maxShowroom_total
        if Showroom_A_End[i] >= Showroom_B_End[i]:
            Showroom_A_End[i] = max(0, Showroom_A_End[i] - excess)
            Inventory_A_End[i] += excess
        else:
            Showroom_B_End[i] = max(0, Showroom_B_End[i] - excess)
            Inventory_B_End[i] += excess

    Shortage_A.append(shortage_A)
    Shortage_B.append(shortage_B)

    # Review period order at end of each cycle
    if i % cycle_len == 0:
        # Order A (mA = 6)
        mA = 6
        available_space_A = maxInventory_total - Inventory_A_End[i] - Inventory_B_End[i]
        order_qty_A = min(mA, available_space_A)
        Order_A.append(order_qty_A)
        lt_A = generate_leadTime()
        LeadTime_A.append(lt_A)
        filling_day_A = i + lt_A + 1  # beginning of business day
        if filling_day_A <= days:
            ComingOrders_A[filling_day_A] += order_qty_A
            AddAtDay_A.append(filling_day_A)
        else:
            AddAtDay_A.append(0)

        # Order B (mB = 6)
        mB = 6
        available_space_B = maxInventory_total - Inventory_A_End[i] - Inventory_B_End[i]
        order_qty_B = min(mB, available_space_B)
        Order_B.append(order_qty_B)
        lt_B = generate_leadTime()
        LeadTime_B.append(lt_B)
        filling_day_B = i + lt_B + 1
        if filling_day_B <= days:
            ComingOrders_B[filling_day_B] += order_qty_B
            AddAtDay_B.append(filling_day_B)
        else:
            AddAtDay_B.append(0)
    else:
        Order_A.append(0)
        LeadTime_A.append(0)
        AddAtDay_A.append(0)
        Order_B.append(0)
        LeadTime_B.append(0)
        AddAtDay_B.append(0)


# Create final table
Table_A = {
    "Days": Days_A,
    "ShA_Begin": Showroom_A_Begin,
    "InvA_Begin": Inventory_A_Begin,
    "Demand_A": Demand_A,
    "ShA_End": Showroom_A_End,
    "InvA_End": Inventory_A_End,
    "Shortage_A": Shortage_A,
    "Replenish_A": Replenish_A,
    "Order_A": Order_A,
    "LT_A": LeadTime_A
}


Table_B = {
    "Days": Days_A,
    "ShB_Begin": Showroom_B_Begin,
    "InvB_Begin": Inventory_B_Begin,
    "Demand_B": Demand_B,
    "ShB_End": Showroom_B_End,
    "InvB_End": Inventory_B_End,
    "Shortage_B": Shortage_B,
    "Replenish_B": Replenish_B,
    "Order_B": Order_B,
    "LT_B": LeadTime_B
}

# Combine tables
table_A = pd.DataFrame(Table_A).drop(0)
table_B = pd.DataFrame(Table_B).drop(0)
combined_table = pd.concat([table_A, table_B.iloc[:, 1:]], axis=1)

print("Electric Appliance Store Simulation Table:")
print(combined_table.head(100))

"""#1- The average ending units in the inventory and the showroom.

"""

# The average ending units in the showroom and histogram
Showroom_A_End_Avg = round(np.mean(Showroom_A_End[1:]), 2)
Showroom_B_End_Avg = round(np.mean(Showroom_B_End[1:]), 2)

print("The Average of Showroom A:", Showroom_A_End_Avg)
print("The Average of Showroom B:", Showroom_B_End_Avg)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10,4))
ax1.hist(Showroom_A_End[1:], alpha=0.7, color='blue')
ax2.hist(Showroom_B_End[1:], alpha=0.7, color='green')
plt.show()

# The average ending units in the inventory and histogram
Inventory_A_End_Avg = round(np.mean(Inventory_A_End[1:]), 2)
Inventory_B_End_Avg = round(np.mean(Inventory_B_End[1:]), 2)

print("The Average of Inventory A:", Inventory_A_End_Avg)
print("The Average of Inventory B:", Inventory_B_End_Avg)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))
ax1.hist(Inventory_A_End[1:], alpha=0.7, color='blue')
ax2.hist(Inventory_B_End[1:], alpha=0.7, color='green')
plt.show()

"""# 2- The number of days when a shortage condition occurs."""

# The number of days when a shortage condition occurs
shortage_days_A = (table_A['Shortage_A'] > 0).sum()
shortage_days_B = (table_B['Shortage_B'] > 0).sum()

print(f"Shortage days A: {shortage_days_A} days ({shortage_days_A/days*100:.1f}%)")
print(f"Shortage days B: {shortage_days_B} days ({shortage_days_B/days*100:.1f}%)")

"""# 3- Do the theoretical average demands of product A and product B match the    experimental ones?"""

# Theoretical average demands
theoretical_demand_A = 0.15*1 + 0.25*2 + 0.25*3 + 0.35*4
theoretical_demand_B = 0.30*1 + 0.30*2 + 0.40*3

# Experimental average demands
experimental_demand_A = round(np.mean(Demand_A[1:]), 2)
experimental_demand_B = round(np.mean(Demand_B[1:]), 2)

print(f"Theoretical Demand A: {theoretical_demand_A:.2f}, Experimental Demand A: {experimental_demand_A:.2f}")
print(f"Theoretical Demand B: {theoretical_demand_B:.2f}, Experimental Demand B: {experimental_demand_B:.2f}")

# Check if they match
tolerance = 0.05
match_A = abs(experimental_demand_A - theoretical_demand_A) <= tolerance
match_B = abs(experimental_demand_B - theoretical_demand_B) <= tolerance

if match_A and match_B:
    print("The theoretical average demands of product A and B match the experimental ones")
elif match_A:
    print("Product A matches, Product B does not match")
elif match_B:
    print("Product A does not match, Product B matches")
else:
    print("The theoretical average demands do not match the experimental ones")

"""# 4- Does the theoretical average lead time of the lead time distribution match the experimental one?"""

# Theoretical average lead time
TheoreticalLeadTime = 0.40*1 + 0.35*2 + 0.25*3

# Experimental average lead time
experimental_lead_times_A = [lt for lt in LeadTime_A[1:] if lt > 0]
experimental_lead_times_B = [lt for lt in LeadTime_B[1:] if lt > 0]
ExperimentalLeadTime_A = round(np.mean(experimental_lead_times_A), 2) if experimental_lead_times_A else 0
ExperimentalLeadTime_B = round(np.mean(experimental_lead_times_B), 2) if experimental_lead_times_B else 0

print(f"Theoretical Lead Time: {TheoreticalLeadTime:.2f}")
print(f"Experimental Lead Time A: {ExperimentalLeadTime_A:.2f}")
print(f"Experimental Lead Time B: {ExperimentalLeadTime_B:.2f}")

# Check if they match
tolerance = 0.05
match_A = abs(ExperimentalLeadTime_A - TheoreticalLeadTime) <= tolerance
match_B = abs(ExperimentalLeadTime_B - TheoreticalLeadTime) <= tolerance

if match_A and match_B:
    print("The theoretical average lead time of the lead time distribution match the experimental one")
elif match_A:
    print("Product A matches, Product B does not match")
elif match_B:
    print("Product A does not match, Product B matches")
else:
    print("The theoretical average lead time of the lead time distribution does not match the experimental one")

"""# 5- Is there a better value for the review period variable N to minimize the shortages in product A and product B?

# 6- Are there better values for mA and mB to minimize the shortages in product A  and product B?
"""